DEFRA/btms-portal-frontend

src/client/stylesheets/application.scss, src/templates/layout.njk, src/templates/search-results.njk
- Increase the width of the UI to help display as much content as possible in the available vertical space
- Display a message when customs declarations are found
- Remove unnecessary CSS
https://eaflood.atlassian.net/browse/CDMS-194
=> CDMS-194: Better align the UI to the user-centred design

.jest/setup-file.js, src/models/pre-notification-model.js, src/services/btms-api-client.js, src/services/search-constants.js, src/services/search-service.js, src/templates/search-results.njk, test/unit/models/pre-notification-model.test.js, test/unit/services/btms-api-client.test.js, test/unit/services/search-service.test.js
The unit test coverage is currently insufficient to satisfy the SonarQube quality gate.
This PR adds new unit tests and also contains some light-touch code improvements/re-factoring
https://eaflood.atlassian.net/browse/CDMS-318
=> CDMS-194: Improve test coverage

package-lock.json, package.json, src/routes/search.js, src/services/index.js, src/services/search-service.js, src/templates/search.njk, test/unit/routes/search.test.js, test/unit/services/search-service.test.js, test/unit/templates/search.test.js, test/unit/templates/template.test.helper.js
Adds input validation of the search term to check for valid value formats.
Checks whether the search term has any results.
https://eaflood.atlassian.net/browse/CDMS-196
=> CDMS 196 search input validation

src/auth/refesh-token.js, src/plugins/auth/defra-id.js, src/services/defraId-client.js, test/unit/auth/refresh-token.test.js, test/unit/auth/user-session.test.js, test/unit/routes/signin-oidc.test.js, test/unit/services/defraId-client.test.js
Add proxy configuration if proxy environment variable is defined
=> CDMS-366: add proxy configuration

.gitignore, README.md, package-lock.json, package.json
optional local env var overrides for dev
=> CDMS-360: use .env.local file if exists for dev

src/models/customs-declaration-model.js, test/unit/models/customs-declaration-model.test.js
https://eaflood.atlassian.net/browse/CDMS-360
Noticed that the duplicate CHEDs were also showing in the matched/unmatched column tooltip.
=> CDMS-360: dedupe unmatched document CHEDS (toolip)

package-lock.json
=> CDMS-532: update browser list

src/client/stylesheets/application.scss, src/models/search-results-model.js, src/templates/search-results.njk, test/unit/models/search-results-model.test.js
https://eaflood.atlassian.net/browse/CDMS-435
=> CDMS-435: add breadcrumbs for search result

src/models/model-constants.js, test/unit/models/pre-notification-model.test.js
No longer close CHED with Rejected status.
=> CDMS-426: close CHED with Replaced status

src/client/stylesheets/_app-search.scss, src/services/search-constants.js, src/services/search-service.js, src/templates/includes/search-button.njk, src/templates/includes/search-hint.njk, src/templates/search.njk, test/unit/services/search-service.test.js, test/unit/templates/search.test.js
https://eaflood.atlassian.net/browse/CDMS-392
Adds the ability to submit a DUCR search but at this point will never return a match as it's still using the old MRN endpoint.
=> CDMS-392: add DUCR to search hint

src/models/customs-declarations.js, src/templates/includes/declaration-summary.njk, test/unit/models/customs-declarations.test.js
https://eaflood.atlassian.net/browse/CDMS-403
=> CDMS-403: display DUCR for declarations

src/models/model-constants.js, test/integration/search-result.test.js, test/unit/models/customs-declarations.test.js
https://eaflood.atlassian.net/browse/CDMS-662
=> CDMS-662: consistent sentence casing of decisions

src/templates/includes/declaration-summary.njk, src/templates/includes/notification-summary.njk, src/templates/macros/highlight-match.njk, test/integration/search-result.test.js, test/unit/templates/search-results.test.js
https://eaflood.atlassian.net/browse/CDMS-666
Highlights MRN, DUCR, CHED or partial CHED searches
=> Search highlighting cdms 666

src/templates/includes/notification-html.njk
If there are no authorities, don't wrap with parens.
https://eaflood.atlassian.net/browse/CDMS-678
=> CDMS-678: selective rendering of authority parens

src/models/pre-notifications.js, test/integration/search-result.test.js, test/unit/models/pre-notifications.test.js
https://eaflood.atlassian.net/browse/CDMS-743
=> CDMS-743: notification model changes

src/auth/check-organisation.js, src/auth/open-id-provider.js, src/config/config.js, src/plugins/auth/open-id.js, test/unit/auth/check-organisation.test.js, test/unit/auth/open-id-provider.test.js
https://eaflood.atlassian.net/browse/CDMS-787
=> CDMS-787: check organisation for DefraId logins

src/auth/check-organisation.js, src/auth/open-id-provider.js, test/unit/auth/check-organisation.test.js, test/unit/auth/open-id-provider.test.js
https://eaflood.atlassian.net/browse/CDMS-816
=> CDMS-816: only check org for DefraId users

src/client/javascripts/application.js, src/client/javascripts/filters.js, src/client/javascripts/search.js, src/client/stylesheets/_landing-page.scss, src/plugins/index.js, src/routes/index.js, src/routes/search-result.js, src/routes/search.js, src/routes/sign-in-entra.js, src/routes/sign-in.js, src/routes/sign-out.js, src/routes/signed-out.js, src/routes/signin-oidc-entra.js, src/routes/signin-oidc.js, src/templates/home.njk, src/templates/layout.njk, test/integration/home.test.js, test/integration/search-result.test.js, test/integration/search.test.js, test/integration/signed-out.test.js, test/integration/signin-oidc-entra.test.js, test/unit/routes/sign-in.test.js, test/unit/routes/sign-out.test.js, test/unit/routes/signin-oidc.test.js
Reverts DEFRA/btms-portal-frontend#79
This was only a temporary amend that is no longer required
=> Revert "CDMS-880: Temporarily remove all routes except home"

src/client/stylesheets/application.scss, src/templates/accessibility.njk, src/templates/cookies.njk, src/templates/error.njk, src/templates/home.njk, src/templates/layout.njk, src/templates/search-result.njk, src/templates/search.njk, src/templates/signed-out.njk, test/integration/accessibility-statement.test.js, test/integration/cookies.test.js, test/integration/error-page.test.js, test/integration/home.test.js, test/integration/search-result.test.js, test/integration/search.test.js, test/integration/signed-out.test.js
Ensure every page title matches it's main heading.
=> CDMS-879: fix page titles

src/models/customs-declarations.js, src/models/pre-notifications.js, src/templates/macros/decision-match.njk, test/unit/models/customs-declarations.test.js, test/unit/models/pre-notifications.test.js
https://eaflood.atlassian.net/browse/CDMS-836
=> CDMS-836: show IUU decision outcomes

src/models/pre-notifications.js, test/unit/models/pre-notifications.test.js
https://eaflood.atlassian.net/browse/CDMS-399
=> CDMS-399: check for null commodityChecks

src/client/javascripts/filters.js, src/templates/includes/declaration-filters.njk, src/templates/includes/notification-filters.njk
https://eaflood.atlassian.net/browse/CDMS-888
=> CDMS-888: fix hiding of filters for non JS

src/templates/macros/commodity-description.njk, test/integration/search-result.test.js, test/unit/templates/search-results.test.js
https://eaflood.atlassian.net/browse/CDMS-889
=> CDMS-889: use ellipsis not three full stops

src/config/config.js, src/plugins/common-view-context.js, src/plugins/security-headers.js, src/templates/includes/google-analytics.njk, src/templates/layout.njk, src/templates/search-result.njk, test/integration/google-analytics.test.js, test/integration/search-result.test.js, test/integration/security-headers.test.js
If a user accept analytics cookies, GTM is added to the page.
=> CDMS-315: Add GTM

src/templates/includes/google-tag-manager-body.njk, src/templates/includes/google-tag-manager-head.njk, src/templates/layout.njk
To fix the issue where tracking information isn't flowing through to google analytics.
[CDMS-315](https://eaflood.atlassian.net/browse/CDMS-315)
[CDMS-315]: https://eaflood.atlassian.net/browse/CDMS-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CDMS-315 - move the google tag manager script to the head element

test/unit/models/customs-declarations.test.js
Other tickets were merged before the previous PR was merged and caused the tests to fail.
=> CDMS-882: Fix test issues

src/models/customs-declarations.js, test/unit/models/customs-declarations.test.js
Some of the test revealed that doc level decisions were not working for certain records.
=> CDMS-798: Fix issue with document level decisions not always working

src/client/stylesheets/_form-auth-provider.scss, src/client/stylesheets/application.scss, src/plugins/security-headers.js, src/plugins/template-renderer/context.js, src/routes/home.js, src/routes/index.js, src/routes/route-constants.js, src/routes/sign-in-choose.js, src/routes/sign-out.js, src/routes/signed-out.js, src/templates/includes/form-auth-provider.njk, src/templates/sign-in-choose.njk, src/templates/signed-out.njk, test/integration/home.test.js, test/integration/security-headers.test.js, test/integration/sign-in-choose.test.js, test/integration/signed-out.test.js, test/unit/plugins/template-rendering/context.test.js, test/utils/capture-form-data.js
Allow user to choose their auth provider when logging in.
https://eaflood.atlassian.net/browse/CDMS-923
=> CDMS-923: consolidate login journey

src/models/model-constants.js
https://eaflood.atlassian.net/browse/CDMS-965
=> CDMS-965: map c085 document codes

src/models/model-constants.js
https://eaflood.atlassian.net/browse/CDMS-965
=> CDMS-965: H218 & H220 can map to C085

src/client/stylesheets/_search-result.scss
https://eaflood.atlassian.net/browse/CDMS-1017
=> CDMS-1017: allow clicking of IPAFFs links

src/models/customs-declarations.js, src/models/pre-notifications.js, test/unit/models/customs-declarations.test.js, test/unit/models/pre-notifications.test.js
When an internalDecisionCode is E88 render the decision description as "Awaiting IPAFFS update"
https://eaflood.atlassian.net/browse/CDMS-1057
=> CDMS-1057: decision of awaiting IPAFFS for E88

README.md, package-lock.json, package.json, src/client/javascripts/reporting.js, src/client/stylesheets/_reporting.scss, src/models/reports.js, src/plugins/template-renderer/vision.js, src/routes/reporting.js, src/services/reporting.js, src/templates/includes/button-reset.njk, src/templates/includes/reporting-filters-shortcuts.njk, src/templates/includes/reporting-filters.njk, src/templates/includes/reporting-reports.njk, src/templates/reporting.njk, src/templates/search-result.njk, src/utils/dates.js, test/integration/reporting.test.js, test/unit/models/reports.test.js, webpack.config.js
Introduce TZ env var
https://eaflood.atlassian.net/browse/CDMS-1055
=> CDMS-1055: add date filtering for reports

package-lock.json, package.json, src/models/reports-csv.js, src/models/reports.js, src/routes/index.js, src/routes/reporting.csv.js, src/routes/reporting.js, src/routes/route-constants.js, src/routes/schemas/date-range.js, src/services/reporting-auth.js, src/services/reporting.csv.js, src/services/reporting.js, src/templates/includes/reporting-reports.njk, src/utils/dates.js, test/integration/reporting.csv.test.js, test/integration/reporting.test.js, test/unit/models/reports.test.js, test/utils/data-stream.js
CDMS-1100: download no matches csv
https://eaflood.atlassian.net/browse/CDMS-1059
&
https://eaflood.atlassian.net/browse/CDMS-1100
=> CDMS-1059: download manual releases csv

src/plugins/common-view-context.js, src/templates/accessibility.njk, src/templates/cookies.njk, src/templates/includes/back-link.njk, src/templates/layout.njk, src/templates/reporting.njk, src/utils/dates.js, test/integration/back-links.test.js
https://eaflood.atlassian.net/browse/CDMS-1115
=> CDMS-1115: back links for orphan pages

eslint.config.js, package-lock.json, package.json, sonar-project.properties, src/client/javascripts/reporting.js, src/client/stylesheets/_reporting.scss, src/client/stylesheets/variables/_colours.scss, src/models/reports.js, src/routes/reporting.js, src/services/reporting.js, src/templates/includes/reporting-charts.njk, src/templates/includes/reporting-filters-shortcuts.njk, src/templates/includes/reporting-filters.njk, src/templates/includes/reporting-reports.njk, src/templates/includes/tiles.njk, src/templates/reporting.njk, src/utils/dates.js, test/integration/reporting.test.js, test/unit/models/reports.test.js
https://eaflood.atlassian.net/browse/CDMS-904
=> CDMS-904: add charts tab to reporting page
